# https://docs.haskellstack.org/en/stable/travis_ci/
# run on containerized infrastructure hopefully
dist: trusty
sudo: false
language: generic


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
- find $HOME/.sbt        -name "*.lock"               -delete

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack ghc -- --version
- travis_wait stack --no-terminal setup
- travis_wait stack --no-terminal test --only-snapshot
- travis_wait stack --no-terminal build

script:
- stack --no-terminal exec tests
- (cd runtime-jvm; sbt main/test:run)
