# https://docs.haskellstack.org/en/stable/travis_ci/
# run on containerized infrastructure hopefully
dist: trusty
sudo: false
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_cache:
# Do any cleanup here to avoid caching junk.

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack ghc -- --version
- stack --no-terminal build

script:
- stack --no-terminal exec tests
- stack --no-terminal exec transcripts
- git status -uno --porcelain # did running transcripts modify any versioned files?
- bash -c '[[ -z $(git status -uno --porcelain) ]]' # abort if it did
