# https://docs.haskellstack.org/en/stable/travis_ci/
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode11.3

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Do any cleanup here to avoid caching junk.
before_cache:
  # this was getting corrupted in the cache for osx ??
  - rm -rf /Users/travis/.stack/setup-exe-cache

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -sSL https://get.haskellstack.org/ | sh

install:
- stack ghc -- --version
- stack --no-terminal build
- stack --no-terminal exec tests
- stack --no-terminal exec transcripts
# fail if running transcripts modified any versioned files
- git diff
- x=`git status --porcelain -uno` bash -c 'if [[ -n $x ]]; then echo "$x" && false; fi'
